### ISSUE TITLE
Compatibility | Chat Heads mod

### ISSUE THREAD

**Issue by Owehttamy** [uku3lig/chathighlighter#3]
While the [Chat Heads](https://modrinth.com/mod/chat-heads) mod works just fine with Chat Highlighter, there is a slight formatting issue where messages that display a head aren't recognized as indented by Chat Highlighter, and instead, highlights slightly to the left of the string.

Example: (Word meant to be highlighted: "Owehttamy")
![image](https://user-images.githubusercontent.com/47429979/210186830-04223c83-901d-4f65-b949-8c0c30b60ef8.png)

**Comment by uku3lig** [comment]
i'll take a look if i can fix it

**Comment by Owehttamy** [comment]
> i'll take a look if i can fix it

#5

**Comment by uku3lig** [comment]
The fix I made is pretty hacky, but for now I can't really do much better because ChatHeads uses Mojang's mappings instead of Yarn, causing unneeded compile-time errors that I can't really work around for now. Perhaps in the future I'll take a deeper look into this, but what I did should work well enough for the time being.

**Comment by iambeingtracked** [comment]
![image](https://github.com/uku3lig/chathighlighter/assets/94642304/0aa2d725-ed1e-4493-a365-1de75e7d57af)
Sometimes it still doesn't work. Not sure if that's because chat heads but still. Also I'm running a 1440p monitor which may be causing such things

**Comment by uku3lig** [comment]
it's not linked to chat head afaik, but to the text being bold. I'll see if i can fix that soon
